# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HireDev' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HireDev
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift'

end
