# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

target 'Hippo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hippo
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/AdMob'
  pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'GoogleParsingUtilities'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftSpinner'
  pod 'DZNEmptyDataSet'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  
  platform :ios, '8.0'
  pod 'SDWebImage'
end

target 'Hippo BuddyBuild' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Hippo
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/AdMob'
  pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'GoogleParsingUtilities'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftSpinner'
  pod 'DZNEmptyDataSet'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  
  platform :ios, '8.0'
  pod 'SDWebImage'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'FontAwesome.swift'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
