# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HireDev' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HireDev
  pod 'Firebase'
  pod 'Firebase/Auth'

  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!

  pod 'FontAwesome.swift'

end
